#!/usr/bin/env bash
set -euo pipefail

# Usage: ./scripts/bump_version.sh <version>
# Example: ./scripts/bump_version.sh 0.2.0
#
# - Updates version in app/pubspec.yaml (auto-increments build number)
# - Regenerates app/lib/core/build_info.dart
# - Commits both files

if [ $# -ne 1 ]; then
  echo "Usage: $0 <version>"
  echo "Example: $0 0.2.0"
  exit 1
fi

VERSION="$1"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PUBSPEC="$REPO_ROOT/app/pubspec.yaml"
BUILD_INFO="$REPO_ROOT/app/lib/core/build_info.dart"

# Read current build number and increment
CURRENT_BUILD=$(grep '^version:' "$PUBSPEC" | sed 's/.*+//')
NEW_BUILD=$((CURRENT_BUILD + 1))

# Update pubspec.yaml (portable sed)
if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' "s/^version: .*/version: $VERSION+$NEW_BUILD/" "$PUBSPEC"
else
  sed -i "s/^version: .*/version: $VERSION+$NEW_BUILD/" "$PUBSPEC"
fi

# Generate build_info.dart
cat > "$BUILD_INFO" << 'DART'
// GENERATED by scripts/bump_version.sh — do not edit manually.
import 'dart:io' show Process;
DART
cat >> "$BUILD_INFO" << EOF
const String appVersion = '$VERSION';
const int appBuildNumber = $NEW_BUILD;
EOF
cat >> "$BUILD_INFO" << 'DART'

// Injected at build time via --dart-define; falls back to git for local dev builds.
const String _buildCommitEnv =
    String.fromEnvironment('BUILD_COMMIT', defaultValue: '');

/// CI injects the full SHA; local dev builds resolve from git.
final String buildCommit = _resolveBuildCommit();

String _resolveBuildCommit() {
  if (_buildCommitEnv.isNotEmpty) return _buildCommitEnv;
  try {
    final result = Process.runSync('git', ['rev-parse', 'HEAD']);
    if (result.exitCode == 0) return (result.stdout as String).trim();
  } catch (_) {}
  return 'dev';
}
DART

# Commit
cd "$REPO_ROOT"
git add "$PUBSPEC" "$BUILD_INFO"
git commit -m "release: v$VERSION"

echo "Bumped to v$VERSION+$NEW_BUILD"
