// GENERATED by scripts/bump_version.sh — do not edit manually.
import 'dart:io' show Process;

const String appVersion = '0.1.1';
const int appBuildNumber = 2;

// Injected at build time via --dart-define; falls back to git for local dev builds.
const String _buildCommitEnv = String.fromEnvironment(
  'BUILD_COMMIT',
  defaultValue: '',
);

/// CI injects the full SHA; local dev builds resolve from git.
final String buildCommit = _resolveBuildCommit();

String _resolveBuildCommit() {
  if (_buildCommitEnv.isNotEmpty) return _buildCommitEnv;
  try {
    final result = Process.runSync('git', ['rev-parse', 'HEAD']);
    if (result.exitCode == 0) return (result.stdout as String).trim();
  } catch (_) {}
  return 'dev';
}
