// GENERATED by scripts/bump_version.sh — do not edit manually.
const String appVersion = '0.1.0';
const int appBuildNumber = 1;
const String buildDate = '2026-04-12';

// Injected at build time via --dart-define; defaults to 'dev' for local builds.
const String buildCommit = String.fromEnvironment('BUILD_COMMIT', defaultValue: 'dev');
